#!/bin/bash

D="${D:-/opt/edx}"
EDX="${EDX:-$D/edx}"
EDX_SYSTEM="${EDX_SYSTEM:-$1}"

case "$EDX_SYSTEM" in
	lms)
		DJANGO_SETTINGS="lms.envs.cms.uji"
		EDX_STATIC_FILES="$D/staticfiles-lms/"
		;;
	cms)
		DJANGO_SETTINGS="cms.envs.uji"
		EDX_STATIC_FILES="$D/staticfiles-cms/"
		;;
	*)
		cat >&2 <<-EOF
		Set EDX_SYSTEM environment variable or pass a value as parameter.
		Ej:
		    EDX_SYSTEM=(lms|cms) $0
		    $0 (lms|cms)
		EOF
		exit 1
		;;
esac

source "$D/env.sh" || { echo "Missing environment";  exit 1; }

for P in django-admin.py xmodule_assets sass rsync
do
	if [ -z "$(which $P)" ]; then
		echo "'$P' is missing" >&2
		exit 1
	fi
done

[ -d "$D/staticfiles" ] && rm -rf "$D/staticfiles" 
[ -d "$D/staticfiles-$EDX_SYSTEM" ] && rm -rf "$D/staticfiles-$EDX_SYSTEM" 

#(cd "$D/edx" && rake lms:gather_assets:cms.uji && mv "$D/staticfiles" "$D/staticfiles-lms/")
django-admin.py preprocess_assets --traceback --settings="$DJANGO_SETTINGS" --pythonpath="$EDX"

xmodule_assets "$EDX"/common/static/xmodule
sass --style compressed --load-path "$EDX"/common/static/sass --require "$EDX"/common/static/sass/bourbon/lib/bourbon.rb --update -E utf-8 "$EDX"/{"$EDX_SYSTEM",common}/static
"$EDX/node_modules/.bin/coffee" --compile "$EDX"

django-admin.py collectstatic --traceback --settings=$DJANGO_SETTINGS --pythonpath="$EDX" --noinput > /dev/null

mv "$D/staticfiles" "$EDX_STATIC_FILES"
rsync -a "$EDX/common/static/" "$EDX_STATIC_FILES/"
rsync -a "$EDX/$EDX_SYSTEM/static/" "$EDX_STATIC_FILES/"
rm -rf -- "$D/staticfiles"

